### ISSUE TITLE
забыли сделать проверку на нулевой указатель 

### ISSUE THREAD

**Issue by MaxGud10** [daniilgriga/Stack-for-hack#1]
Daniilgriga, good evening. You have made two unpleasant mistakes that could put your data in danger

When you push data onto the stack, you forget to add a verification executioner. you have this function called: 
```STACK_ASSERT(stack, file, line, func);```
It is needed to prevent an attack on the null pointer.
Here's how I suggest tweaking the code so that this attack can be prevented:
```
int stack_push (struct stack_str* stack, stack_elem_t elem ON_DBG(, const char* file, int line, const char* func))
{

    STACK_ASSERT(stack, file, line, func);

    increasing_capacity (stack ON_DBG(, file, line, func));

    stack->data[stack->size++] = elem;

    ON_HASH ( calculate_hash(stack); )

    STACK_ASSERT(stack, file, line, func);

    return 0;
}
```

I understand that you sleep very little and you have a heavy workload, but such an oversight on the part of the programmer is unacceptable.
If I were you, I would think: "Is the profession of a programmer exactly right for me?"

**Comment by daniilgriga** [comment]
hi, thanks for the information, bro. I really didn't sleep that night, thank you!

**Comment by daniilgriga** [comment]
fixed it, thanks!
